trigger:
- main

prerequisites:
- agent: Ubuntu-SelfHostedAgent

jobs:
- job: PrintHelloWorld
  steps:
  - script: |
      for i in {1..10}
      do
          echo "Hola Mundo $i"
      done
    displayName: 'Imprimir Hola Mundo'
    parallel: true

- job: CreateAndPrintFiles
  steps:
  - script: |
      for i in {1..10}
      do
          filename="file_$i_$(date +'%Y%m%d%H%M%S').txt"
          touch $filename
          echo "Created $filename"
      done
    displayName: 'Crear y Mostrar Archivos'
    parallel: true
